// <auto-generated />
using System;
using CmeTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CmeTracker.Api.Migrations
{
    [DbContext(typeof(CmeTrackerDbContext))]
    partial class CmeTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CmeTracker.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.CMERequirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"));

                    b.Property<int>("PeriodYear")
                        .HasColumnType("int");

                    b.Property<int>("RequiredHours")
                        .HasColumnType("int");

                    b.HasKey("RequirementId");

                    b.ToTable("CMERequirements");

                    b.HasData(
                        new
                        {
                            RequirementId = 1,
                            PeriodYear = 1,
                            RequiredHours = 24
                        },
                        new
                        {
                            RequirementId = 2,
                            PeriodYear = 2,
                            RequiredHours = 48
                        },
                        new
                        {
                            RequirementId = 3,
                            PeriodYear = 5,
                            RequiredHours = 120
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentCode = "KHNT",
                            DepartmentName = "Khoa Ngoại Tổng hợp"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentCode = "KHITT",
                            DepartmentName = "Khoa Nội Tổng hợp"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentCode = "KHSAN",
                            DepartmentName = "Khoa Sản"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentCode = "KHNHI",
                            DepartmentName = "Khoa Nhi"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentCode = "KHCC",
                            DepartmentName = "Khoa Cấp cứu"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentCode = "GMHS",
                            DepartmentName = "Khoa Gây mê Hồi sức"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentCode = "KHXN",
                            DepartmentName = "Khoa Xét nghiệm"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentCode = "CDHA",
                            DepartmentName = "Khoa Chẩn đoán hình ảnh"
                        },
                        new
                        {
                            DepartmentId = 9,
                            DepartmentCode = "DUOC",
                            DepartmentName = "Khoa Dược"
                        },
                        new
                        {
                            DepartmentId = 10,
                            DepartmentCode = "PHNS",
                            DepartmentName = "Phòng Nhân sự"
                        },
                        new
                        {
                            DepartmentId = 11,
                            DepartmentCode = "PHKT",
                            DepartmentName = "Phòng Kế toán"
                        },
                        new
                        {
                            DepartmentId = 12,
                            DepartmentCode = "PHHC",
                            DepartmentName = "Phòng Hành chính"
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            DepartmentId = 1,
                            EmployeeCode = "NV001",
                            FullName = "Nguyễn Văn An",
                            Gender = "Nam",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2010, 8, 1),
                            Position = "Bác sĩ"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            DepartmentId = 2,
                            EmployeeCode = "NV002",
                            FullName = "Trần Thị Bình",
                            Gender = "Nữ",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2015, 1, 15),
                            Position = "Điều dưỡng"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateOnly(1978, 11, 5),
                            DepartmentId = 5,
                            EmployeeCode = "NV003",
                            FullName = "Lê Hoàng Cường",
                            Gender = "Nam",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2005, 6, 1),
                            Position = "Bác sĩ"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateOnly(1992, 4, 18),
                            DepartmentId = 3,
                            EmployeeCode = "NV004",
                            FullName = "Phạm Thị Dung",
                            Gender = "Nữ",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2018, 3, 10),
                            Position = "Hộ sinh"
                        },
                        new
                        {
                            EmployeeId = 5,
                            DateOfBirth = new DateOnly(1988, 9, 30),
                            DepartmentId = 6,
                            EmployeeCode = "NV005",
                            FullName = "Hoàng Minh Đức",
                            Gender = "Nam",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2013, 5, 20),
                            Position = "Bác sĩ"
                        },
                        new
                        {
                            EmployeeId = 6,
                            DateOfBirth = new DateOnly(1995, 2, 14),
                            DepartmentId = 4,
                            EmployeeCode = "NV006",
                            FullName = "Ngô Thị Hoa",
                            Gender = "Nữ",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2020, 7, 1),
                            Position = "Điều dưỡng"
                        },
                        new
                        {
                            EmployeeId = 7,
                            DateOfBirth = new DateOnly(1982, 6, 25),
                            DepartmentId = 7,
                            EmployeeCode = "NV007",
                            FullName = "Vũ Quốc Hùng",
                            Gender = "Nam",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2008, 9, 15),
                            Position = "Kỹ thuật viên"
                        },
                        new
                        {
                            EmployeeId = 8,
                            DateOfBirth = new DateOnly(1993, 12, 8),
                            DepartmentId = 8,
                            EmployeeCode = "NV008",
                            FullName = "Đặng Thị Lan",
                            Gender = "Nữ",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2017, 4, 22),
                            Position = "Kỹ thuật viên"
                        },
                        new
                        {
                            EmployeeId = 9,
                            DateOfBirth = new DateOnly(1975, 8, 16),
                            DepartmentId = 1,
                            EmployeeCode = "NV009",
                            FullName = "Bùi Văn Minh",
                            Gender = "Nam",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2000, 1, 10),
                            Position = "Bác sĩ trưởng"
                        },
                        new
                        {
                            EmployeeId = 10,
                            DateOfBirth = new DateOnly(1991, 5, 3),
                            DepartmentId = 9,
                            EmployeeCode = "NV010",
                            FullName = "Đinh Thị Nga",
                            Gender = "Nữ",
                            IsActive = true,
                            IsDeleted = false,
                            JoinDate = new DateOnly(2016, 8, 30),
                            Position = "Dược sĩ"
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<int>("ActualHours")
                        .HasColumnType("int");

                    b.Property<string>("CertificateFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingHours")
                        .HasColumnType("int");

                    b.HasKey("TrainingId");

                    b.HasIndex("CourseId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTrainings");

                    b.HasData(
                        new
                        {
                            TrainingId = 1,
                            ActualHours = 0,
                            CourseId = 1,
                            EmployeeId = 1,
                            ExpiryDate = new DateOnly(2026, 7, 5),
                            IssueDate = new DateOnly(2025, 6, 15),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 2,
                            ActualHours = 0,
                            CourseId = 2,
                            EmployeeId = 1,
                            ExpiryDate = new DateOnly(2026, 12, 30),
                            IssueDate = new DateOnly(2025, 12, 17),
                            TrainingHours = 16
                        },
                        new
                        {
                            TrainingId = 3,
                            ActualHours = 0,
                            CourseId = 2,
                            EmployeeId = 2,
                            ExpiryDate = new DateOnly(2026, 5, 1),
                            IssueDate = new DateOnly(2023, 12, 28),
                            TrainingHours = 16
                        },
                        new
                        {
                            TrainingId = 4,
                            ActualHours = 0,
                            CourseId = 4,
                            EmployeeId = 2,
                            ExpiryDate = new DateOnly(2027, 1, 1),
                            IssueDate = new DateOnly(2025, 11, 28),
                            TrainingHours = 8
                        },
                        new
                        {
                            TrainingId = 5,
                            ActualHours = 0,
                            CourseId = 3,
                            EmployeeId = 3,
                            ExpiryDate = new DateOnly(2027, 2, 10),
                            IssueDate = new DateOnly(2026, 1, 16),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 6,
                            ActualHours = 0,
                            CourseId = 9,
                            EmployeeId = 3,
                            ExpiryDate = new DateOnly(2027, 6, 30),
                            IssueDate = new DateOnly(2026, 3, 7),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 7,
                            ActualHours = 0,
                            CourseId = 5,
                            EmployeeId = 4,
                            ExpiryDate = new DateOnly(2027, 5, 11),
                            IssueDate = new DateOnly(2026, 3, 17),
                            TrainingHours = 8
                        },
                        new
                        {
                            TrainingId = 8,
                            ActualHours = 0,
                            CourseId = 8,
                            EmployeeId = 5,
                            ExpiryDate = new DateOnly(2026, 6, 5),
                            IssueDate = new DateOnly(2024, 5, 11),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 9,
                            ActualHours = 0,
                            CourseId = 9,
                            EmployeeId = 5,
                            ExpiryDate = new DateOnly(2026, 11, 12),
                            IssueDate = new DateOnly(2026, 1, 6),
                            TrainingHours = 16
                        },
                        new
                        {
                            TrainingId = 10,
                            ActualHours = 0,
                            CourseId = 4,
                            EmployeeId = 6,
                            ExpiryDate = new DateOnly(2026, 7, 30),
                            IssueDate = new DateOnly(2025, 7, 30),
                            TrainingHours = 8
                        },
                        new
                        {
                            TrainingId = 11,
                            ActualHours = 0,
                            CourseId = 6,
                            EmployeeId = 7,
                            ExpiryDate = new DateOnly(2027, 2, 28),
                            IssueDate = new DateOnly(2025, 11, 28),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 12,
                            ActualHours = 0,
                            CourseId = 2,
                            EmployeeId = 7,
                            ExpiryDate = new DateOnly(2027, 8, 19),
                            IssueDate = new DateOnly(2026, 2, 15),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 13,
                            ActualHours = 0,
                            CourseId = 7,
                            EmployeeId = 8,
                            ExpiryDate = new DateOnly(2026, 8, 9),
                            IssueDate = new DateOnly(2025, 8, 19),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 14,
                            ActualHours = 0,
                            CourseId = 2,
                            EmployeeId = 8,
                            ExpiryDate = new DateOnly(2027, 7, 19),
                            IssueDate = new DateOnly(2026, 1, 16),
                            TrainingHours = 16
                        },
                        new
                        {
                            TrainingId = 15,
                            ActualHours = 0,
                            CourseId = 3,
                            EmployeeId = 9,
                            ExpiryDate = new DateOnly(2027, 11, 6),
                            IssueDate = new DateOnly(2026, 1, 6),
                            TrainingHours = 48
                        },
                        new
                        {
                            TrainingId = 16,
                            ActualHours = 0,
                            CourseId = 10,
                            EmployeeId = 10,
                            ExpiryDate = new DateOnly(2027, 6, 10),
                            IssueDate = new DateOnly(2025, 9, 9),
                            TrainingHours = 24
                        },
                        new
                        {
                            TrainingId = 17,
                            ActualHours = 0,
                            CourseId = 2,
                            EmployeeId = 10,
                            ExpiryDate = new DateOnly(2027, 8, 29),
                            IssueDate = new DateOnly(2026, 2, 5),
                            TrainingHours = 16
                        },
                        new
                        {
                            TrainingId = 18,
                            ActualHours = 0,
                            CourseId = 4,
                            EmployeeId = 10,
                            ExpiryDate = new DateOnly(2027, 11, 27),
                            IssueDate = new DateOnly(2026, 3, 17),
                            TrainingHours = 8
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "ExpiryWarningDays",
                            SettingValue = "60"
                        },
                        new
                        {
                            SettingKey = "UrgentWarningDays",
                            SettingValue = "30"
                        },
                        new
                        {
                            SettingKey = "RequiredHours1Year",
                            SettingValue = "24"
                        },
                        new
                        {
                            SettingKey = "RequiredHours2Years",
                            SettingValue = "48"
                        },
                        new
                        {
                            SettingKey = "RequiredHours5Years",
                            SettingValue = "120"
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.TrainingCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("TrainingCourses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseCode = "PALS",
                            CourseName = "Cấp cứu Nhi khoa nâng cao (PALS)",
                            DefaultHours = 24,
                            Organizer = "BV Nhi Đồng 1"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseCode = "KSNK",
                            CourseName = "Kiểm soát nhiễm khuẩn cơ bản",
                            DefaultHours = 16,
                            Organizer = "Sở Y tế Đồng Nai"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseCode = "ACLS",
                            CourseName = "Hỗ trợ sự sống tim mạch nâng cao (ACLS)",
                            DefaultHours = 24,
                            Organizer = "Hội Tim mạch VN"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseCode = "BLS",
                            CourseName = "Hồi sức tích cực cơ bản (BLS)",
                            DefaultHours = 8,
                            Organizer = "Hội Tim mạch VN"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseCode = "ALSO",
                            CourseName = "Hỗ trợ sự sống sản khoa (ALSO)",
                            DefaultHours = 32,
                            Organizer = "BV Từ Dũ"
                        },
                        new
                        {
                            CourseId = 6,
                            CourseCode = "HLATM",
                            CourseName = "Huyết học lâm sàng",
                            DefaultHours = 24,
                            Organizer = "Viện Huyết học"
                        },
                        new
                        {
                            CourseId = 7,
                            CourseCode = "SAUCB",
                            CourseName = "Kỹ thuật siêu âm cơ bản",
                            DefaultHours = 24,
                            Organizer = "Hội CĐHA VN"
                        },
                        new
                        {
                            CourseId = 8,
                            CourseCode = "GMNS",
                            CourseName = "Gây mê nhi khoa",
                            DefaultHours = 24,
                            Organizer = "BV Nhi Đồng 2"
                        },
                        new
                        {
                            CourseId = 9,
                            CourseCode = "ATPT",
                            CourseName = "An toàn phẫu thuật WHO",
                            DefaultHours = 16,
                            Organizer = "WHO / BV Từ Dũ"
                        },
                        new
                        {
                            CourseId = 10,
                            CourseCode = "DUOCLAM",
                            CourseName = "Dược lâm sàng nâng cao",
                            DefaultHours = 24,
                            Organizer = "Hội Dược học VN"
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hệ thống Admin",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAsPedAj4aoWYEaYTcQv1oXbXdyldgqfpEs5RSRKg+4gC/T8z3IJkpNmVMnTO1vfVQ==",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ngân Thị",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAASPkgrHWGulQ5hmf1XpMwRSyRvX8Cif2YptGSLtPowI0FNmqx1wiTjolaF8C24kg==",
                            Role = "HR",
                            Username = "hr"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Văn Quản Lý",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEIdW1mKN3kbQkQG0z4ALK8hMdqURDPJyTxoakTfqmaw0jYR3MLuVlXWYdY/dE0PBZA==",
                            Role = "Manager",
                            Username = "manager"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn Xem",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEARBDgxamUgpBRchcSOm4pvj7iNsrqq/CST3xpJXbiTqf0/ZFP0UBQ8dGo/BfyyMRw==",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Employee", b =>
                {
                    b.HasOne("CmeTracker.Api.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.EmployeeTraining", b =>
                {
                    b.HasOne("CmeTracker.Api.Models.TrainingCourse", "Course")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CmeTracker.Api.Models.Employee", "Employee")
                        .WithMany("Trainings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Notification", b =>
                {
                    b.HasOne("CmeTracker.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.User", b =>
                {
                    b.HasOne("CmeTracker.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.Employee", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("CmeTracker.Api.Models.TrainingCourse", b =>
                {
                    b.Navigation("EmployeeTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
